In [1]:
import numpy as np

In [2]:
# 1 create an array 'arr'of integers from 0 to 5 and print its data type 
arr=np.array([0,1,2,3,4,5])
arr.dtype

dtype('int64')

In [3]:
#2 given a np array 'arr', check if its data type is float64
arr=np.array([1.5,2.6,3.7])
#this array is given in the question 

arr.dtype=='float64'

True

In [4]:
# 3. create a numpy array 'arr' with a data type of complex 128 containing three complex number
arr=np.array([3,6,5],dtype='complex128')
arr

array([3.+0.j, 6.+0.j, 5.+0.j])

In [5]:
# 4 convert an existing numpy array 'arr'of integers to float32 data type 
arr=np.array([5,6,8,9])
float32=np.float32(arr)          
float32

array([5., 6., 8., 9.], dtype=float32)

In [6]:
# 5 given a numpy array arr with float64 data type, convert it to float 32 to reduce decimal precision. 
arr=np.array([1.500500,2.4000,3.054500])
# this is other way to change the data type
#arr1=arr.astype(np.float32)        
arr1=np.float32(arr)

arr1

array([1.5005, 2.4   , 3.0545], dtype=float32)

In [7]:
#6. create a functiion array_attributes that takrs a numpy array as input and return input shape,size,and 
# data type.
def arr_attributes(arr):
    arr1=np.array(arr)
    shape=arr1.shape
    size=arr1.size
    dtype=arr1.dtype
    return [shape , size, dtype]
#print("array shape is:",shape)
#print("array size:",size)
#print("array type is:",dtype)    
arr_attributes([[1,2],
                [2,3],
                [4,5]])    

[(3, 2), 6, dtype('int64')]

In [8]:
#7 create a function array_dimension that takes a numpy array as input and returns its dimensionality.
import numpy as np
def array_dimension(input_arr):
    arr1=np.asanyarray(input_arr)
    #n=list[input("enter the array element with commas: ")]
    return arr1.ndim
array_dimension([[1,2,3],[4,5,6],[7,8,9]])

2

In [9]:
#8. design a function item_size_info that takes a numpy array as input and returns the item size and the total size in bytes.
def item_size_info(input1_arr):
    input_arr=np.array(input1_arr)
    
    item_size=input_arr.itemsize 
    
    # itemsize = 8, and 4 item size(total size) =32 
    
    total_size=input_arr.nbytes
    return 'item_size',item_size,'total_size', total_size

item_size_info([[6,7],[4,7]])    
      

('item_size', 8, 'total_size', 32)

In [10]:
# 9. create a function array_strides that takes a numpy array as input and returns the strides of the array.
import numpy as np
def array_strides(arr):
    return arr.strides
array_strides(np.random.randint(1,9,(3,4)))

(32, 8)

In [11]:
#10 design a function shape_stride_relationship that takes a numpy array as input and returns the shape and stride of the array.
def shape_strides_relationship(arr1):
    shape=arr1.shape
    strides=arr1.strides
    return shape, strides
shape_strides_relationship(np.random.randint(1,8,(3,3)))

((3, 3), (24, 8))

In [12]:
#11. create a fuction 'create_zeros_array' that takes an integer 'n' as input and returns a numpy array of zeros with 'n' elements.
def create_zeros_array(n):
    arr=np.zeros(n,dtype = 'int')
    return arr
create_zeros_array(5)

array([0, 0, 0, 0, 0])

In [13]:
# 12. write a function create ones matrix that takes integers rows and columns as input and generates 2d numpy array filled with ones of size rows*cols
def create_ones_matrix(a, b):
    arr1=np.ones((a, b))
    new_arr=np.mat(arr1)
    return new_arr

create_ones_matrix(4 ,3)

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
#13  write a function 'generate_range_array' that takes three integers starts, stop, and step as argumentrs and create a numpy array with a range starting from start, ending at stop (exclusive) and with the specified step.
def generate_range_array(start, stop, step):
    arr=np.arange(start, stop, step)
    return arr
generate_range_array(1,9,2)

array([1, 3, 5, 7])

In [15]:
# 14.design a function 'generate_linear_space' that takes two floats two float 'start','stop','num' and one 'int' as arguments and generates a numpy arrauy with num equally spaced values between start and stop (inclusive).
def generate_linear_space(start,stop,num):
    arr=np.linspace(start,stop,num)
    
    return arr

generate_linear_space(2.5,5.8,6)

# it takes two float 'start','stop','num' and one 'int'

array([2.5 , 3.16, 3.82, 4.48, 5.14, 5.8 ])

In [16]:
# 15. cretae a function 'create_identity_matrix' that takes an intgers 'n' a input and generte a square identity matrix of size 'n*n' using 'numpy.eye',
def create_identity_matrix(n):
    arr=np.eye(n,dtype = int)
    return arr
create_identity_matrix(4)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [17]:
# 16. write a function that takes a python list and converts it into a numpy array.
def py_list(input_list1):
    
    return np.array(input_list1)

py_list([1,2,5,3,6,4,7,8,5])    

array([1, 2, 5, 3, 6, 4, 7, 8, 5])

In [18]:
# 17. create a numpy array and demonstrat the use of 'numpy.view' to crete a numpy array.
import numpy as np

original_array=np.array([1,2,3,4,5])
view_array=original_array.view()

print("original array")
print(original_array)
print("\nview array")
print(view_array)
#modify the view array

view_array[0]=99

print("after modifying original array")
print(original_array)
print("\nafter modifying view array")
print(view_array)

# this is a concept of shalow copy.

original array
[1 2 3 4 5]

view array
[1 2 3 4 5]
after modifying original array
[99  2  3  4  5]

after modifying view array
[99  2  3  4  5]


In [19]:
# 18   write a function that takes two numpy arrays and concatinates them along a specified axis.
arr1=np.array([[1, 5, 5],
               [5,7,9]])

arr2=np.array([[1, 5, 5]])

concates=np.concatenate((arr1, arr2), axis=0)

print('arr1 is : ',arr1)
print('arr2 is : ',arr2)
print('concates : ',concates)

arr1 is :  [[1 5 5]
 [5 7 9]]
arr2 is :  [[1 5 5]]
concates :  [[1 5 5]
 [5 7 9]
 [1 5 5]]


In [20]:
# 19 create to numpy array  with diffferent shapes and concatenates them horizonttallly using numpy
arr1=np.array([[2,3],[4,5],[6,7]])
arr2=np.array([[2,3,9],[4,8,5],[9,4,5]])

concate_array=np.concatenate((arr1,arr2),axis=1)

print('array1')
print(arr1)
print("\narray2")
print(arr2)
print("\nconcate_array")
print(concate_array)


array1
[[2 3]
 [4 5]
 [6 7]]

array2
[[2 3 9]
 [4 8 5]
 [9 4 5]]

concate_array
[[2 3 2 3 9]
 [4 5 4 8 5]
 [6 7 9 4 5]]


In [21]:
#20 Write a function that vertically stacks multiple numpy arrays given as a list.
def vertically_stacks(array):
    return np.vstack(array)
vertically_stacks([(np.array([1,2,3])),(np.array([4,5,6])),(np.array([7,8,9]))])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# 21. write a python function using numpy to create an array of integers within a specified range (inclusive) with a given step size.
def create_array_integers(start,end,step):
    return np.arange(start,end,step)
create_array_integers(1,8,2)

array([1, 3, 5, 7])

In [23]:
# 22.write a python function using numpy to generate an arry of 10 equally spaced values between 0 and 1 (inclusive)
def equally_spaced_array(start,end,vlues):
    return np.linspace(start,end,vlues)
equally_spaced_array(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
#23.write a python function using numpy to create an array of 5 logerithmically spaced values between 1 and 1000(inclusive).
def  logorithmically_spaced_values(start,stop,num):
    log1=np.log10(start)
    log2=np.log10(stop)
    return np.logspace(log1,log2,num)
logorithmically_spaced_values(1,1000,5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [25]:
#24.Create a pandas dataframe using a numpy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
df=pd.DataFrame(np.random.randint(1,101,(5,3)))
df

0   1   2
0   25  75  98
1  100   1  31
2   38   1  22
3   80  51  17
4   21  55  83

In [26]:
#25.write a function that takes a pandas dataframe and replace all negaative values in a specific column with zeros. use numpy operation within the pndas dataframe.

data={'A': [1,-2, 3, 4,-5],
      'B': [6, 7,-8,-9,10]}
def replace_negative_with_zeros(df,column_name):
    df[column_name] = np.where(df[column_name]<0, 0 ,df[column_name])
    return  df[column_name]
replace_negative_with_zeros(pd.DataFrame(data),'B')

0     6
1     7
2     0
3     0
4    10
Name: B, dtype: int64

In [27]:
#26 access the third element from the given numpy array
arr=np.array([10,20,30,40,50])  
# this arr given in the question
arr[2]


30

In [28]:
# 27.retrieve the element at index (1,2) from the 2d numpy array.
arr=np.array([[1,2,3,],
              [4,5,6,],
              [7,8,9]])
# retrieve the element at index (1,2) from the 2D numpy array
new_arr=arr[1, 2]
new_arr


6

In [29]:
#28. using boolean indexing, extract elements greater than 5 from the given numpy array.
arr=np.array ([3,8,2,10,5,7])
extract_aray=arr[arr>5]
extract_aray

array([ 8, 10,  7])

In [30]:
#29. perform basic slicing to extrct elements from index 2 to 5 (inclusive) from the given numpy array.
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]


array([3, 4, 5, 6])

In [31]:
#30. slice the 2d numpy array to extract the sub-array '[[2,3],[5,6]]' from the given array.
arr_2D=np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr_2D[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [32]:
#31. write a numpy function to extarct elements in specific order from a gievn 2d array based on indices provided in another array.
 
    
import numpy as np
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])    
 
indices=[[0,1],[1,2],[2,0]]
    
def extract_elements(array, indices):
    indices=np.array(indices)
    if indices.shape[1] != 2:
        raise valueError('indices have must shape(n,2)')
        
# advanced indexing to extarct elemsnts
    extact_elements= array[indices[:, 0 ], indices [:, 1]]
    return extact_elements
extract_elements(array,indices)    

array([2, 6, 7])

In [33]:
# 32. create a numpy function that filters elements greater than a threshold from a given 1d array using boolean indexing
import numpy as np
def filter_elements(array,threshold):
    filtered_elements=array[array>threshold]
    return filtered_elements
filter_elements(np.array([1,2,3,6,5,4,8,9,23]),5)

array([ 6,  8,  9, 23])

In [34]:
# 33. incomplered 

# 3D arrayy
array=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]],
                
                [[19,20,21],
                 [22,23,24],
                 [25,26,27]]])

# 3 indices
x_indices=[0,1,2]
y_indices=[1,2,0]
z_indices=[2,0,1]

def  extract_elements(array,x_indices,y_indices,z_indices):
    x_indices=np.array(x_indices)
    y_indices=np.array(y_indices)
    z_indices=np.array(z_indices)
    
    if not (x_indices.shape == y_indices.shape == z_indices.shape):
        raise ValueError('all indices array must have the same shape')
    
    extacted_elements=array[x_indices,y_indices,z_indices]
    return extacted_elements

extract_elements(array,x_indices,y_indices,z_indices)   

array([ 6, 16, 20])

In [35]:
#34. write a numpy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def function_returns(val, condition1, condition2):
    arr=np.array(val)
    elements= arr[arr<condition1]
    elements2=elements[elements>condition2]
    return list(elements2)
function_returns([2,3,1,4,5,6,4,7,89,0,7,6,43,8,79],7,2)

[3, 4, 5, 6, 4, 6]

In [36]:
#35.Create a python function that extarct elements from a 2D array using row an colmn indices provided in a seprate array.

array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
row_indices=[0,1,2]
col_indices=[1,2,0]
def extact_elements_2D(array,row_indices, col_indices):
    row_indices=np.array(row_indices)
    col_indices=np.array(col_indices)
    extract_elements=array[row_indices, col_indices]
    return extract_elements
extact_elements_2D(array,row_indices, col_indices)

array([2, 6, 7])

In [37]:
# 36. given an array arr of shape (3,3), add a scaler value of 5 to each element using numpy broadcasting.
arr=np.ones((3,3))
scaler=5
arr+scaler

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [38]:
#37. consider two arrayy arr1 of shape(1,3) and arr2 of shape(3,4). multiply each row of arr2 by the coresponding element of arr1 using numpy brodcasting.

#given array
arr=np.array([[7, 8, 9]])
# arr shape with(1,3)

arr1=arr.T
# transpose array

arr2=np.array([[1,2,3,4],
               [5,6,7,8],
               [8,9,10,11]])
# multiply in each row of arr2 with each element of arr1
arr2*arr1

array([[ 7, 14, 21, 28],
       [40, 48, 56, 64],
       [72, 81, 90, 99]])

In [39]:
# 38. given a 1D array arr1 of shape(1,4) and 2D array of arr2 of shape (4,3), add arr1 to each row of arr2 using numpy broadcasting.

#given array arr
arr=np.array([1,2,3,4])
#  transpose axis in 1D
arr1=arr[:,np.newaxis]


arr2=np.array([[1, 5, 7],
               [2, 4, 9],
               [7, 5, 8],
               [3, 6, 9]])

arr1+arr2

array([[ 2,  6,  8],
       [ 4,  6, 11],
       [10,  8, 11],
       [ 7, 10, 13]])

In [40]:
#39. consider two arrays arr1 of shape(3,1) and arr2 of shape (1,3). add these arrays using numpy broadcasting.
arr1=np.random.randint(1,8,(3,1))
arr2=np.random.randint(1,8,(1,3))
print ('array1',np.array(arr1))
print('\narray2',np.array(arr2))
arr1+arr2

array1 [[6]
 [1]
 [2]]

array2 [[6 6 7]]


array([[12, 12, 13],
       [ 7,  7,  8],
       [ 8,  8,  9]])

In [41]:
#40 given array arr1 of shape (2,3) and arr2 of shape(2,2), perform multipliction using numpy broadcasting. handle the shape incompatibility.

arr1=np.random.randint(1,9,(2,3))
#arr1.reshape(2,2,3)

arr2=np.random.randint(1,9,(2,2))
# reshaping the array
new_arr2=arr2.reshape(2,2,1)

multiplication=arr1*new_arr2

print('array 1 is : \n', arr1)
print('\narray 2 after reshaping is : \n', new_arr2)
print('\nmultiplication is : \n',multiplication)

array 1 is : 
 [[5 7 2]
 [6 7 8]]

array 2 after reshaping is : 
 [[[3]
  [1]]

 [[4]
  [2]]]

multiplication is : 
 [[[15 21  6]
  [ 6  7  8]]

 [[20 28  8]
  [12 14 16]]]


In [42]:
#41 calculate the column_wise mean for the given array
# given array is
arr=np.array([[1,2,3],
              [4,5,6]])

np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

In [43]:
#42. find maximum value in each row of the given array:
# given array is
arr=np.array([[1,2,3],
              [4,5,6]])

print("max value of 1st row:",np.max(arr[0]))
print("max value of 2nd row:",np.max(arr[1]))

max value of 1st row: 3
max value of 2nd row: 6


In [44]:
# 43.for the given array, find indices of maximum value in each column.
# given array arr=np.array([[1,2,3],[4,5,6]])

arr=np.array([[1,2,3],
              [4,5,6]])

# maximum element in each columnn
np.argmax(arr,axis=0)

array([1, 1, 1])

In [45]:
# 44.for the given array, apply custom function to calculate moving sum along rows.

# given array 
#arr=np.array([[1,2,3],[4,5,6]])

def cum_sum(row):
    return np.cumsum(row,axis=1)
cum_sum([[1,2,3], [4,5,6]])

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [46]:
# 45.in the given array, check if all elements in ech columns are even.
# given array is  >>>  arr=np.array([[2,4,6],[3,5,7]])

arr=np.array([[2,4,6],[3,5,7]])
even_check=(arr % 2 == 0 )
all_check=np.all(even_check, axis=0)

print(all_check)

# the output is

[False False False]


In [47]:
# 46. given a numpy array arr, reshape it into a matrix of dimentions 'm' rows and 'n' columns. return the reshape matrix.
#the given array is 

original_array=np. array([1,2,3,4,5,6])

np.matrix(original_array.reshape(3,2))

#(rows) m=3, (colunms) n=2

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [48]:
# 47. create  function that takes a matrix as input and returns the flattened array.
# given matrix is

input_matrix = np.matrix([[1,2,3],[4,5,6]])
def mat_func(input_matrix):
    
    flatten_mat= np.array(input_matrix.flatten())
    
    return flatten_mat

mat_func(input_matrix)


array([[1, 2, 3, 4, 5, 6]])

In [49]:
#48.write a function that concatentes two given arrays along a specified axis.

#given two arrays
array1=np.array([[1,2], [3,4]])
array2=np.array([[5,6], [7,8]])

np.concatenate((array1,array2), axis=0)

# we can also do for this axis
#np.concatenate((array1,array2), axis=1)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
# 49. create a function that splits an array into multiple sub arrays along specified axis.

# given array
original_array= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr=np.split(original_array, 3 , axis=0)

# 3 is a no.of elements that you ends the split
arr

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [51]:
#50. write a function that inserts and then deletes elements from a given array at specified indices.
# given arrays
original_array=np.array([1,2,3,4,5])
indices_to_insert=[2,4]
values_to_insert=[10,11]
indices_to_delete=[1,3]

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    modified_array=original_array.tolist()
    
    for index, value in zip(indices_to_insert, values_to_insert):
        modified_array.insert(index, value)
    
    for index in sorted(indices_to_delete, reverse=True):
        del modified_array[index]
        
    modified_array=np.array(modified_array)
    
    return modified_array

insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

array([ 1, 10, 11,  4,  5])

In [52]:
# 51. create a numpy array arr1 with random integers and another array arr2 with integers from 1 to 10. perfrom element wise addition between arr1 and arr2.
import numpy as np
arr1=np.random.randint(0,12,10)
print(arr1)

arr2=np.arange(1,11)
print('\n',arr2)

print('\nafter alement wise addition')
arr1+arr2

[0 0 7 5 1 0 5 2 1 6]

 [ 1  2  3  4  5  6  7  8  9 10]

after alement wise addition


array([ 1,  2, 10,  9,  6,  6, 12, 10, 10, 16])

In [53]:
#52.genate a numpy array arr1 with squential integers from 10 to 1 and another array arr2 with integers from 1 to 10. subtrct arr2 from arr1 element wise.
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
print('array1\n',arr1)
print('\narray2\n',arr2)
print('\n')
arr1-arr2

array1
 [10  9  8  7  6  5  4  3  2  1]

array2
 [ 1  2  3  4  5  6  7  8  9 10]




array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [54]:
#53.create a numpy array arr1 with random integers and another array arr2 with intgers from 1 to 5. perform elemnt wise multiplication between arr1 and arr2.
arr1=np.random.randint(0,10,5)
arr2=np.arange(1,6)
print(arr1,'\n')
print(arr2,'\n')
print('the multiplication is')
arr1*arr2

[6 5 2 3 4] 

[1 2 3 4 5] 

the multiplication is


array([ 6, 10,  6, 12, 20])

In [55]:
#54. Generate a numpy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. perform element_wise division of arr1 by arr2.
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
print('array1\n',arr1)
print('array2\n',arr2)
print('\nthe division is')
arr1/arr2

array1
 [ 2  4  6  8 10]
array2
 [1 2 3 4 5]

the division is


array([2., 2., 2., 2., 2.])

In [56]:
#55.Create a numpy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. calculate the exponatial of arr1 raised to the power of arr2 elemnet_wise.
arr1=np.arange(1,6)
arr2=arr1[::-1]
power=np.power(arr1,arr2)
print('array1 : \n',arr1)
print('\narray2 : \n',arr2)
print('\nelement_wise power is : \n',power)

array1 : 
 [1 2 3 4 5]

array2 : 
 [5 4 3 2 1]

element_wise power is : 
 [ 1 16 27 16  5]


In [57]:
# 56. write a function that count the occurences of a specific substring within a numpy array of strings.
# given array
#arr=np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_occurence(arr,substring):
    count=np.char.count(arr,substring)
    total_count=np.sum(count)
    return total_count

count_occurence(['hello', 'world', 'hello', 'numpy', 'hello'], substring= 'hello')  

3

In [58]:
# 57. incomplete
def extract_upper(arr):
    ch=[]
    for string in arr:
        uppercase_string= ''.join([char for char in string if char.isupper()])
        ch.append(uppercase_string)
    return ch
extract_upper (['Hello','World','GPT'])

['H', 'W', 'GPT']

In [59]:
#58.write a function that replace occurenece of a substring in a numpy array of strings with a new string

def replace_occurence(arr,old_substring,new_substring):
    return np.char.replace(arr,old_substring,new_substring)

replace_occurence(['apple', 'banana', 'grapes', 'pineapple'],'apple', 'lichi')

array(['lichi', 'banana', 'grapes', 'pinelichi'], dtype='<U9')

In [60]:
#59. write a function that concatenates strings in a numpy array elements-wise.
# the given arrays are

arr1=np.array(['hello', 'world'])
arr2=np.array(['open','AI'])

np.char.add(arr1,arr2)

array(['helloopen', 'worldAI'], dtype='<U9')

In [61]:
#60.write a function that finds the length of th longest string in a numpy array.
# given array

arr=np.array(['apple','banan','grapes','pineapple'])
length=np.vectorize(len)(arr)

print (np.max(length))

9


In [62]:
#61.create a dataset of 100 random intgers between 1 and 1000. compute the mean, median, variance, and standard deviation of the dataset using numpy's function.
dataset=np.random.randint(1,1001,100)
print('the mean is : ',np.mean(dataset))
print('\nthe median is : ',np.median(dataset))
print('\nthe variance is : ',np.var(dataset))
print('\nthe standard daviation is : ',np.std(dataset))

the mean is :  423.93

the median is :  348.5

the variance is :  91687.4251

the standard daviation is :  302.79931489354465


In [63]:
#62.Generate an array of 50 random numbers between 1 and 100. find the 25th and 75th percentiles of the dataset.
arr=np.random.randint(1,101,size=50)

percentile_25=np.percentile(arr,25)
percentile_75=np.percentile(arr,75)

print('percentile 25 is : ',percentile_25)

print('\npercentile 75 is : ',percentile_75)

percentile 25 is :  41.0

percentile 75 is :  74.0


In [64]:
#63.Create two arrays representing two sets of variables. computethe correlation coefficiant between these arrays using numpy's corrcoef function.
set1=np.array([1,2,3,4,5])
set2=np.array([6,7,8,9,10])
a=np.corrcoef(set1, set2)
print(a)

[[1. 1.]
 [1. 1.]]


In [65]:
#64.create two matrices and perform matrix multiplication using numpy's 'dot' function.

mat1=np.mat([[1,2],[3,4]])
mat2=np.mat([[6,7,8],[9,10,11]])
np.dot(mat1,mat2)

matrix([[24, 27, 30],
        [54, 61, 68]])

In [66]:
#65.Create an array of 50 integers between 10 and 1000. calculate the 10th, 50th (median), and 90th percentiles along with the first and third quatiles.

arr=np.random.randint(10,1001,50)
percentile=np.percentile(arr, [10,25,50,75,90])
first_quartile=np.percentile(arr,25)

third_quartile=np.percentile(arr,75)

print('\npercentile 10 : ',percentile[0])
print('\npercentile 50 : ',percentile[2])
print('\npercentile 90 : ',percentile[4])
print('\nfirst quartile : ',first_quartile)
print('\nthird quartile : ',third_quartile)



percentile 10 :  129.0

percentile 50 :  479.5

percentile 90 :  945.1

first quartile :  221.75

third quartile :  783.75


In [67]:
#66.create an array of integers and find the index of a specific element.
arr=np.array([11,12,13,14,15,16,17,18,19,20])

# element to find
element_to_find=15
np.where(arr==element_to_find)[0]

array([4])

In [68]:
# 67.Generate a random numpy array and sort it in ascending order.
arr=np.random.randint(1,10,10)

np.sort(arr,axis=-1)

array([2, 2, 3, 4, 5, 6, 8, 9, 9, 9])

In [69]:
#68.Filter elements >20 in the given numpy array.
arr=np.array([1,25,6,42,8,30])
new_element=arr[arr>20]
new_element

array([25, 42, 30])

In [70]:
# 69.Filter elements which are divisile by 3 from a given numpy array.
# given array is 
arr=np.array([1,5,8,12,15])

divisible_array=arr[arr % 3 == 0]
divisible_array

array([12, 15])

In [71]:
#70.Filter elements whch are >= 20 and <= 40 from a given numoy array.
# given array is 
arr=np.array([10,20,30,40,50])

new_array=arr[arr>=20]
filter_element= new_array[new_array<=40]
filter_element

array([20, 30, 40])

In [72]:
#71.for the given numpy array, check its bytes order using the dtype attribtes byteorder.
# the given array

arr=np.array([1,2,3])
arr.dtype.byteorder
# it is in native by order

'='

In [73]:
#72.for the given numpy array. perform byte swapping in place using 'byteswap()'.
# the given array

arr=np.array([1,2,3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [74]:
#73.For the given numpy array, swape its byte order without modifying the original array using new byteorder.
# given array 
arr=np.array([1,2,3], dtype=np.int32)
swaped_array=arr.newbyteorder()
print('original array : ',arr)
print('swaped byte order array : ',swaped_array)

original array :  [1 2 3]
swaped byte order array :  [16777216 33554432 50331648]


In [75]:
#74.for the given numpy array and swap its byte order conditionally based on system endianness using 'newbyteorder'.
arr=np.array([1,2,3],dtype=np.int32)

# '=' means the system default endianness
if arr.dtype.byteorder =='=':
    arr=arr.newbyteorder('>')
else:
    arr=arr.newbyteorder('<')
print (arr)


[16777216 33554432 50331648]


In [76]:
#75. for the given numpy array, check if byte swapping is necessery for thr current system using 'dtype' attribute 'byteorder'.
arr=np.array([1,2,3],dtype=np.int32)
if arr.dtype.byteorder=='=':
    swapped_array=arr.newbyteorder('>')
    print('byte swapping is ncessery.')
    print('original array:',arr)
    print('swapped array:',swapped_array)

byte swapping is ncessery.
original array: [1 2 3]
swapped array: [16777216 33554432 50331648]


In [77]:
#76. create a numpy array arr1 with values from 1 to 10. create a copy of arr1 named copy_arr and modify an element in copy_arr. check if modifying copy_arr affects arr1.
arr=np.arange(1,11)
copy_arr=arr.copy()
print('original array : ',arr)
copy_arr[3]=45
print('\ncopy array : ',copy_arr)
print('\nmodifyig affects : ',np.array_equal(arr,copy_arr))

original array :  [ 1  2  3  4  5  6  7  8  9 10]

copy array :  [ 1  2  3 45  5  6  7  8  9 10]

modifyig affects :  False


In [78]:
#77.cerae a 2D numpy array 'matix' of shape (3,3) with random integers. extract a sloice view_slice from the mtrix modify an element in view_slice and observe if it changes the origial 'matix'.
matrix=np.random.randint(1,10,(3,3))  
view_slice=matrix[:2,:2]
view_slice[0,0]=99
print('matrix\n',matrix)
print('\nview slice\n',view_slice)
#view_slice=matrix.view
#view_slice


matrix
 [[99  3  2]
 [ 8  4  1]
 [ 2  7  9]]

view slice
 [[99  3]
 [ 8  4]]


In [79]:
#78.Create a numpy array 'array_a' of shape (4,3) with sequential integers from 1 to 12. Extract a slice 'view_b' from 'array_a' and broadcast the addition of 5 to view_b. checkk if it others the original 'array_a'
array_a=np.arange(1,13).reshape(4,3)
view_b=array_a[:2,:2]
view_b+=5
print('original array after modification\n',array_a)
print('\nview slice after modification\n',view_b)


original array after modification
 [[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

view slice after modification
 [[ 6  7]
 [ 9 10]]


In [80]:
#79.Create a numpy array 'org_array' of shape(2,4) with vlues from 1 to 8. create a reshape view 'reshaped_view' of shape (4,2) from original array. modify an element in 'reshaped_view' and check if it reflects changes in the original 'orig_array.'
orig_array=np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])
reshaped_view=orig_array.reshape(4,2)
reshaped_view[0,0]=99
print('original array\n',orig_array)
print('\nreshaped array\n',reshaped_view)


original array
 [[99  2  3  4]
 [ 5  6  7  8]]

reshaped array
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [81]:
#80.create a nmpy array 'data' of shape (3,4) with random integers. Extract a copy 'data_copy' of elements greater than 5. Modify an element in 'data_copy' and verify if it effects the original'data'.
data=np.random.randint(1,13,size=(3,4))
print('original data\n',data)
data_copy=data[data>5].copy()
data_copy[0]=99
print('\ndata copy\n',)
print(data_copy)
print('\noriginal data after modification\n',data)

original data
 [[ 5  9  5  5]
 [11  5  8  7]
 [ 2  7  4  8]]

data copy

[99 11  8  7  7  8]

original data after modification
 [[ 5  9  5  5]
 [11  5  8  7]
 [ 2  7  4  8]]


In [82]:
#81.Create two matrix A and B of identical shape containing integers and perform addition and subtract operations between them.
shape=(3,4)
A=np.random.randint(0,10,size=shape)
print('mtrixs A\n',A)
B=np.random.randint(0,10,size=shape)
print('\nmtrixs B\n',B)
print('\naddition is\n',A+B)
print('\nsubtraction  is\n',A-B)

mtrixs A
 [[1 5 7 1]
 [3 9 5 3]
 [9 3 5 8]]

mtrixs B
 [[2 6 4 3]
 [2 0 3 5]
 [2 9 6 7]]

addition is
 [[ 3 11 11  4]
 [ 5  9  8  8]
 [11 12 11 15]]

subtraction  is
 [[-1 -1  3 -2]
 [ 1  9  2 -2]
 [ 7 -6 -1  1]]


In [83]:
# 82.Generate two matrices 'C' (3*2) and 'D' (2*4) and perform matrix multiplication.

C=np.mat([[1,2],[3,4],[5,6]])
print('matrix C\n',C)

D=np.mat([[7,8,9,10],[11,12,13,14]])
print('\nmatrix D\n',D)
# in multiplicqtion matix shape muust be (column of first matrix is equals to row of scond matrix)
print('\nmultiplication\n',(C * D))

matrix C
 [[1 2]
 [3 4]
 [5 6]]

matrix D
 [[ 7  8  9 10]
 [11 12 13 14]]

multiplication
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [84]:
# 83.Create a matrix 'E' and find its transpose.
E=np.mat([[7, 8, 9, 10],
          [11, 12, 13, 14]])
 #for matrix transpose
print('transpose of matrix is\n',E.T)

transpose of matrix is
 [[ 7 11]
 [ 8 12]
 [ 9 13]
 [10 14]]


In [85]:
#84.Generate a square matrix 'F' and compute its determinant.
#a square matrix F is(the elements are between 0 to 1(exclusive)) 
F=np.random.rand(4,4)
print('this is a squre mtrix\n',F)

# for determinant using liner algebra det
print('\nthe determinant is \n',np.linalg.det(F))

this is a squre mtrix
 [[0.37964731 0.05149371 0.27003444 0.53612118]
 [0.17304773 0.09886092 0.97248253 0.89487802]
 [0.90328259 0.41324829 0.47189392 0.07931357]
 [0.14716628 0.51055088 0.84505213 0.39420365]]

the determinant is 
 -0.10845716432353966


In [86]:
#85.create a sqauare mattrix 'G' and find its inverse.
#(the elements are between 0 to 1(exclusive))
G=np.random.rand(4,4)
print('this is a squre mtrix\n',G)

# here is a linearlgebra inverse of mtrix
print('\nthe inverse mtrix is \n',np.linalg.inv(G))

this is a squre mtrix
 [[0.69336688 0.85552983 0.78107152 0.1385891 ]
 [0.38963007 0.43628465 0.90710809 0.28826672]
 [0.10884465 0.09851925 0.48887895 0.84510505]
 [0.32122884 0.04484267 0.40464068 0.46843059]]

the inverse mtrix is 
 [[ 0.69554937 -1.35614005 -1.79341402  3.86430298]
 [ 1.6637789  -1.05464626  1.68485917 -2.8829142 ]
 [-1.23610748  2.57003605 -0.52323343 -0.27188152]
 [ 0.43152724 -1.18911251  1.52053319 -0.00434149]]
